spring:
  application:
    name: OrderManagement
  datasource:
    url: jdbc:mysql://localhost:3306/ordermanagement2_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 63998380
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    debug: true
server:
  port: 8092