spring:
   application:
     name: ProductManagement1
   datasource:
    url: jdbc:mysql://localhost:3306/ProductManagement1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
server:
  port: 8085